//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7311
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public string empEmail { get; set; }
        public string empLocation { get; set; }
        public string empPhoneNumber { get; set; }
        public int empTypeId { get; set; }
        public int empPwdId { get; set; }
    
        public virtual EmpType EmpType { get; set; }
        public virtual Password Password { get; set; }
    }
}
