//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7311
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int listId { get; set; }
        public int farmerId { get; set; }
        public int prodTypeId { get; set; }
    
        public virtual Farmer Farmer { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
