//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7311
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStore
    {
        public int prodId { get; set; }
        public int prodQty { get; set; }
        public int prodRemaining { get; set; }
        public int ProdTypeId { get; set; }
        public System.DateTime ProdDateAdded { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
